SELECT MP.ORGANIZATION_CODE,
       MSI.SEGMENT1 ASSET_GROUP,
       mcst.category_set_name,
       MCB.SEGMENT1 MAJOR_CATEGORY,
       MCB.SEGMENT2 MINOR_CATEGORY,'  ' " ",SRC.ORGANIZATION,SRC.ASSET_GROUP,
        SRC.STRUCTURE_NAME,SRC.MAJOR_CATEGORY,SRC.MINOR_CATEGORY
FROM    MTL_SYSTEM_ITEMS MSI,
        MTL_PARAMETERS MP,
        RD_ASSET_GRP_ASSET_CTG@PDSEBS2DPPRD SRC,
        mtl_categories_b MCB,
        mtl_category_sets_b mcs,
        mtl_category_sets_tl mcst,
        MTL_ITEM_CATEGORIES MIC
WHERE   MSI.ORGANIZATION_ID=MP.MASTER_ORGANIZATION_ID
  AND   MSI.SEGMENT1=SRC.ASSET_GROUP
  AND   MP.ORGANIZATION_CODE=SRC.ORGANIZATION
  AND   MCB.segment1=SRC.MAJOR_CATEGORY
  AND   MCB.SEGMENT2=SRC.MINOR_CATEGORY
  AND   mcb.structure_id    =mcs.structure_id
  AND   mcst.category_set_id=mcs.category_set_id
  AND   MIC.INVENTORY_ITEM_ID(+)=MSI.INVENTORY_ITEM_ID
  AND   MIC.ORGANIZATION_ID(+)=MSI.ORGANIZATION_ID
  AND   MIC.CATEGORY_ID(+)=MCB.CATEGORY_ID
  AND   MIC.category_set_id(+)=MCS.category_set_id;
