SELECT  MP.ORGANIZATION_CODE,AST_GRP.SEGMENT1 ASSET_GROUP,
        CII.INSTANCE_NUMBER ASSET_NUMBER,
        MSI.SEGMENT1  ACTIVITY,
        MEAA.CLASS_CODE,
        MEAA.LAST_SCHEDULED_END_DATE,
        MEAA.LAST_SCHEDULED_START_DATE,'  ' " ",
        SRC.ORGANIZATION SRC_ORGANIZATION,
        SRC.ASSET_GROUP	SRC_ASSET_GROUP,
        SRC.ASSET_NUMBER SRC_ASSET_NUMBER,
        SRC.ACTIVITY	SRC_ACTIVITY,
        SRC.LS_ACT_ST_DT	SRC_LS_ACT_ST_DT,
        SRC.LS_ACT_ED_DT	SRC_LS_ACT_ED_DT,
        SRC.METER_NAME	SRC_METER_NAME,
        SRC.LS_READING SRC_LS_READING

FROM    mtl_eam_asset_activities    MEAA,
        CSI_ITEM_INSTANCES CII,
        MTL_SYSTEM_ITEMS  MSI,
        MTL_SYSTEM_ITEMS  AST_GRP,
        ATP_ASSET_LAST_SERV_INFO@PDSEBS2DPPRD  SRC,
	mtl_parameters mp
WHERE   MEAA.MAINTENANCE_OBJECT_ID=CII.INSTANCE_ID
  AND   MEAA.ASSET_ACTIVITY_ID=MSI.INVENTORY_ITEM_ID
  AND   MSI.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID
  AND   AST_GRP.INVENTORY_ITEM_ID=CII.INVENTORY_ITEM_ID
  AND   AST_GRP.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID
  AND   CII.INSTANCE_NUMBER=SRC.ASSET_NUMBER
  AND   MSI.SEGMENT1=SRC.ACTIVITY
  AND   MP.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID;
