  SELECT MP.ORGANIZATION_CODE,AST_GRP.SEGMENT1 ASSET_GROUP,
        MSI.SEGMENT1  ACTIVITY,
        MEAA.CLASS_CODE,
        MEAA.start_date_active,
        MEAA.end_date_active,
        CII.INSTANCE_NUMBER ASSET_NUMBER,
        WORK_ORDER_TYPE , '  ' " ",SRC.ORGANIZATION,SRC.ASSET_GROUP,SRC.ACTIVITY,
        SRC.WIP_ACC_CLASS,SRC.EFFEC_DT_FROM,SRC.EFFEC_DT_TO,SRC.ASSET_NUMBER,
        SRC.WO_TYPE_CODE
FROM    mtl_eam_asset_activities    MEAA,
        CSI_ITEM_INSTANCES CII,
        MTL_SYSTEM_ITEMS  MSI,
        MTL_SYSTEM_ITEMS  AST_GRP,
        ATP_ASSET_ACTIVITY@PDSEBS2DPPRD  SRC,
        mtl_parameters mp,
        EAM_ORG_MAINT_DEFAULTS EOMD
WHERE   MEAA.MAINTENANCE_OBJECT_ID=CII.INSTANCE_ID
  AND   MEAA.ASSET_ACTIVITY_ID=MSI.INVENTORY_ITEM_ID
  AND   MSI.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID
  AND   AST_GRP.INVENTORY_ITEM_ID=CII.INVENTORY_ITEM_ID
  AND   AST_GRP.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID
  AND   CII.INSTANCE_NUMBER=SRC.ASSET_NUMBER
  AND   MSI.SEGMENT1=SRC.ACTIVITY
  and   mp.organization_code=src.organization
  and   mp.organization_id=CII.LAST_VLD_ORGANIZATION_ID
  AND   MEAA.activity_association_id=EOMD.OBJECT_ID 
  and eomd.organization_id =MSI.ORGANIZATION_ID
  and eomd.object_type=60;
