SELECT  MP.ORGANIZATION_CODE,
        mas.assignment_set_name,
        MAS.DESCRIPTION,
        (SELECT MEANING
        FROM FND_LOOKUP_VALUES
        WHERE LOOKUP_TYPE='MRP_ASSIGNMENT_TYPE'
        AND LOOKUP_CODE=MSA.ASSIGNMENT_TYPE) ASSIGNMENT_TYPE,
        msa.entity_name,
        (SELECT MEANING
         FROM  FND_LOOKUP_VALUES
         WHERE LOOKUP_TYPE='MRP_SOURCING_RULE_TYPE'
          AND  LOOKUP_CODE=SOURCING_RULE_TYPE) SOURCING_RULE_TYPE,
          msa.sourcing_rule_name, '  ' " ",SRC.ORGANIZATION,
          SRC.ASSIGNMENT_SET, SRC.ASSIGNMENT_SET_DSC,
          SRC.ASSIGNED_TO, SRC.ITEM_NUMBER, SRC.TYPE_SOURCING_RULE,
          SRC.SRC_RULE_NAME
FROM    MRP_ASSIGNMENT_SETS MAS,
        MTL_PARAMETERS MP,
        MRP_SR_ASSIGNMENTS_V MSA,
       RD_SOURCING_RULE_ASGNMT_SET@PDSEBS2DPPRD SRC
WHERE   MP.ORGANIZATION_ID=MSA.ORGANIZATION_ID
  AND   msa.assignment_set_id=mas.assignment_set_id
  AND   SRC.ORGANIZATION=MP.ORGANIZATION_CODE
  AND   MAS.assignment_set_name=SRC.ASSIGNMENT_SET
  AND   msa.entity_name=SRC.ITEM_NUMBER
 
