  SELECT MP.ORGANIZATION_CODE,EPS.NAME SCHEDULE_NAME,
      EPSR.DAY_INTERVAL BASE_INTERVAL_DAYS,
      (EPSR.DAY_INTERVAL*EPS.INTERVAL_PER_CYCLE) CYCLE_INTERVAL_DAYS,EPS.FROM_EFFECTIVE_DATE,EPS.TO_EFFECTIVE_DATE,'  ' " ",
      SRC.ORGANIZATION, SRC.SCHEDULE_NAME, SRC.BASE_INTERVAL_DAYS, SRC.CYCLE_INTERVAL_DAYS,
      SRC.EFFEC_DT_FROM, SRC.EFFEC_DT_TO
FROM    eam_pm_scheduling_rules EPSR,
      eam_pm_schedulings  EPS,
        (SELECT DISTINCT * FROM ATP_PM_DATE_RULE@PDSEBS2DPPRD) SRC,
        CSI_ITEM_INSTANCES CII,
        MTL_PARAMETERS MP
WHERE   EPSR.PM_SCHEDULE_ID=EPS.PM_SCHEDULE_ID
  AND   EPSR.RULE_TYPE=1
  AND   EPS.NAME=SRC.SCHEDULE_NAME
  AND   CII.INSTANCE_ID=EPS.MAINTENANCE_OBJECT_ID
  AND   MP.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID
;
