SELECT MP.ORGANIZATION_CODE,EPS.NAME SCHEDULE_NAME,
        MSI.SEGMENT1 ACTIVITY_NAME,
        EPA.INTERVAL_MULTIPLE,
        DECODE(EPA.ALLOW_REPEAT_IN_CYCLE,'Y','Yes','N','No') REPEAT_IN_CYCLE,
        EPA.DAY_TOLERANCE,'  ' " ",SRC.ORGANIZATION,SRC.SCHEDULE_NAME,
        SRC.ACTIVITY_NAME, SRC.INTERVAL_MULTIPLE, SRC.REPEAT_IN_CYCLE,
        SRC.TOLERANCE_IN_DAYS
FROM    eam_pm_activities EPA,
        eam_pm_schedulings EPS,
        mtl_eam_asset_activities MEAA,
        mtl_system_items  MSI,
        CSI_ITEM_INSTANCES CII,
        ATP_PM_ACTIVITY@PDSEBS2DPPRD SRC,
        mtl_parameters mp
WHERE EPS.PM_SCHEDULE_ID=EPA.PM_SCHEDULE_ID
  AND MEAA.ACTIVITY_ASSOCIATION_ID=EPA.ACTIVITY_ASSOCIATION_ID
  AND MSI.INVENTORY_ITEM_ID=MEAA.ASSET_ACTIVITY_ID
  AND meaa.maintenance_object_id=cii.instance_id
  AND MSI.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID
  AND EPS.maintenance_object_id=cii.instance_id
  AND EPS.NAME=SRC.SCHEDULE_NAME
  AND MSI.SEGMENT1=SRC.ACTIVITY_NAME
  AND MP.ORGANIZATION_ID=CII.LAST_VLD_ORGANIZATION_ID;
